version: '3.5'

services:
  main_service:
    build: .
    command: sh -c "crond -f"
    restart: on-failure:5
    env_file:
      - ./config/${ENVIRONMENT:-dev}/service_variables.env
    volumes:
      - data_vol:/data
      - log_vol:/log
      - ./config/${ENVIRONMENT:-dev}/cron.d:/etc/cron.d

volumes:
  data_vol:
    name: ${ENVIRONMENT:-dev}_data_vol
    driver: local
  log_vol:
    name: ${ENVIRONMENT:-dev}_log_vol
    driver: local